from typing import Any, ClassVar

from hare.fields.data.uuids import UUIDField
from hare.query.expressions.base.constant_expression import ConstantExpression
from hare.query.expressions.base.expression_context import ExpressionContext
from hare.query.expressions.base.expression_result import ExpressionResult
from hare.sql.terms.functions.function import Function


class RandomUUID(ConstantExpression):
    """A random version 4 UUID - ``gen_random_uuid()``, generated by the database per row.

    Example: ``Token.objects.filter(expired=True).update(key=RandomUUID())``
    """

    #: Shared, long-lived instance - the statement plans hold output fields weakly.
    OUTPUT_FIELD: ClassVar[UUIDField[Any]] = UUIDField()

    populate_field_object = True

    def get_result(self, expression_context: ExpressionContext) -> ExpressionResult:
        return ExpressionResult(term=Function("gen_random_uuid"), output_field=self.OUTPUT_FIELD)  # type: ignore[call-overload]

    value_field = OUTPUT_FIELD
