from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import TYPE_CHECKING, Any, Self, cast
from uuid import uuid4

from hare import fields
from hare.contrib.outbox.constants import (
    ENQUEUE_ARGUMENT_FIELD_NAMES,
    OUTBOX_KEY_MAX_LENGTH,
    OUTBOX_WAKEUP_META_OPTION,
    RELAY_MANAGED_FIELD_NAMES,
)
from hare.contrib.outbox.outbox_json_encoding import OutboxJsonEncoding
from hare.core.connections.connections import Connections
from hare.ddl.constraints.unique_constraint import UniqueConstraint
from hare.ddl.indexes.index import Index
from hare.ddl.indexes.partial_index import PartialIndex
from hare.dialects.base.client.database_client import DatabaseClient
from hare.dialects.base.client.transaction_client import TransactionClient
from hare.exceptions import ConfigurationError, IntegrityError, ValidationError
from hare.models import Model
from hare.models.tenancy.tenancy import Tenancy
from hare.query.expressions import Q

if TYPE_CHECKING:  # pragma: nocoverage
    from hare.contrib.outbox.wakeups.outbox_wakeup import OutboxWakeup


class OutboxEvent(Model):
    """A transactional outbox row: written by ``enqueue()`` - or by ``Meta.change_capture`` of a
    captured model - in the transaction of the change it reports, and delivered afterwards by an
    ``OutboxRelay``.

    Combine with your own project's base model through multiple inheritance:

    Example:
        class MyOutboxEvent(YourBaseModel, OutboxEvent):
            class Meta(YourBaseModel.Meta, OutboxEvent.Meta):
                outbox_wakeup = ListenNotifyWakeup()

    ``Meta.outbox_wakeup`` is the wakeup the events of the model signal once their transaction
    commits - the relay subscribes to it; none to rely on the relay's polling.

    ``OutboxEvent.Meta`` declares only ``abstract = True`` and the relay's own ``indexes`` on
    purpose - ``ModelMeta`` merges every abstract ancestor's ``Meta`` attrs via a reversed-MRO
    walk, and lets whichever ancestor comes later in that walk win on a key collision. Adding
    anything else to this Meta (a ``table`` name, ...) would risk colliding with
    ``YourBaseModel.Meta``.

    Attributes:
        sequence: The primary key, generated by the database - the order the relay delivers in.
            Events of one row are written under that row's lock, so their order is the order of
            their commits whatever the clocks of the hosts.
        id: The event's own id - the key a receiver deduplicates on.
        ordering_key: Events of one key are delivered strictly in order; None for none.
        headers: Metadata of the event besides its payload - a trace context, the author of a
            change - carried into the headers of a Kafka, RabbitMQ or HTTP message.
        next_attempt_at: When a failed event is tried again; None for at once.
        lease_until, leased_by: The relay delivering the event and until when it may.
        dead_lettered_at: When the event ran out of attempts - it is no longer delivered.
    """

    sequence = fields.BigIntField(primary_key=True)
    id = fields.UUIDField(default=uuid4, unique=True)
    topic = fields.CharField(max_length=OUTBOX_KEY_MAX_LENGTH)
    payload = fields.JSONField[Any](encoder=OutboxJsonEncoding.dumps)
    headers = fields.JSONField[dict[str, Any]](encoder=OutboxJsonEncoding.dumps, default=dict)
    ordering_key = fields.CharField(max_length=OUTBOX_KEY_MAX_LENGTH, null=True)
    # Set only by enqueue(idempotency_key=...). Unique, but NULLs never conflict with each other
    # (PostgreSQL and SQLite alike), so rows enqueued without a key are unaffected.
    idempotency_key = fields.CharField(max_length=OUTBOX_KEY_MAX_LENGTH, null=True, unique=True)
    created_at = fields.DatetimeField(auto_now_add=True)
    attempts = fields.IntField(default=0)
    last_error = fields.TextField(null=True)
    next_attempt_at = fields.DatetimeField(null=True)
    lease_until = fields.DatetimeField(null=True)
    leased_by = fields.CharField(max_length=OUTBOX_KEY_MAX_LENGTH, null=True)
    published_at = fields.DatetimeField(null=True)
    dead_lettered_at = fields.DatetimeField(null=True)

    class Meta:
        abstract = True
        indexes = (
            Index(fields=("topic", "sequence")),
            # The relay's queue - the rows still to deliver, in order.
            PartialIndex(fields=("sequence",), condition=Q(published_at__isnull=True, dead_lettered_at__isnull=True)),
            # An earlier undelivered event of the same ordering key holds a row back.
            PartialIndex(fields=("ordering_key", "sequence"), condition=Q(published_at__isnull=True)),
            PartialIndex(fields=("published_at",), condition=Q(published_at__isnull=False)),
            PartialIndex(fields=("dead_lettered_at",), condition=Q(dead_lettered_at__isnull=False)),
        )

    @classmethod
    def get_wakeup(cls) -> OutboxWakeup | None:
        """The wakeup the events of the model signal - ``Meta.outbox_wakeup``.

        Returns:
            The wakeup, None when the model declares none.
        """
        return getattr(cls._meta.meta, OUTBOX_WAKEUP_META_OPTION, None)

    @classmethod
    async def enqueue(
        cls,
        topic: str,
        payload: Any,
        *,
        using: str | DatabaseClient | None = None,
        idempotency_key: str | None = None,
        ordering_key: str | None = None,
        headers: Mapping[str, Any] | None = None,
        extra_field_values: Mapping[str, Any] | None = None,
        wakeup: OutboxWakeup | None = None,
    ) -> Self:
        """Writes an outbox event - atomic with the caller's own write when called inside
        ``Transactions.atomic()`` on the same connection. Once the transaction commits (at once
        outside a transaction) the wakeup signals the relays.

        Args:
            topic: The event's topic - a delivery routes on it.
            payload: The event's payload - JSON values, or values ``OutboxJsonEncoding`` writes.
            using: The connection to write on instead of the model's.
            idempotency_key: At most one event ever exists per key: when one already exists, it is
                returned unchanged instead of writing a new one - no error, no duplicate. Written as
                ``INSERT ... ON CONFLICT (idempotency_key) DO NOTHING`` and a ``SELECT``, so a key
                conflict never aborts an enclosing transaction.
            ordering_key: Events of one key are delivered strictly in the order they were written.
            headers: Metadata of the event besides its payload.
            extra_field_values: Values of the columns a subclass declares on top of
                ``OutboxEvent``'s own.
            wakeup: The wakeup to signal instead of the model's ``Meta.outbox_wakeup``.

        Returns:
            The event - the one already stored under ``idempotency_key`` when there is one.

        Raises:
            ValidationError: ``topic``, ``idempotency_key`` or ``ordering_key`` isn't text of 1 to
                255 characters, ``headers`` isn't a mapping of text keys, or ``extra_field_values``
                sets a field ``enqueue()`` or ``OutboxRelay`` sets itself.
            ValidationError: The payload or the headers hold a value without a JSON form here
                (``OutboxJsonEncoding``).
            IntegrityError: ``idempotency_key`` conflicts with an event this call can't see - another
                tenant's, or one committed after this transaction's snapshot; or the event violates
                another unique constraint.
            ConfigurationError: ``using`` wasn't given, the model's connection has no open
                transaction and another connection has one - the event would commit on its own
                instead of with that transaction's write. Pass ``using=`` if this is intended.
        """
        cls.validate_enqueue_options(topic, idempotency_key, ordering_key, headers, extra_field_values)
        field_values = dict(extra_field_values or {})
        write_connection = cls.get_write_connection(using)
        if idempotency_key is None:
            event = await cls.objects.using(write_connection).create(
                topic=topic, payload=payload, ordering_key=ordering_key, headers=dict(headers or {}), **field_values
            )
            is_new = True
        else:
            event, is_new = await cls.insert_or_get_by_idempotency_key(
                topic, payload, idempotency_key, ordering_key, dict(headers or {}), write_connection, field_values
            )
        if is_new:
            await cls.signal_wakeup(write_connection, (topic,), wakeup)
        return event

    @classmethod
    def get_write_connection(cls, using: str | DatabaseClient | None) -> DatabaseClient:
        """The connection an event is written on.

        Args:
            using: The connection asked for, None for the model's.

        Returns:
            The connection.

        Raises:
            ConfigurationError: ``using`` wasn't given, the model's connection has no open
                transaction and another connection has one.
        """
        if using is not None:
            return cast("DatabaseClient", Connections.get_client(using))
        write_connection = cls.get_connection(for_write=True)
        if not write_connection.is_transaction_client:
            for connection_alias in Connections.aliases():
                if connection_alias != write_connection.connection_alias and isinstance(
                    Connections.get(connection_alias), TransactionClient
                ):
                    raise ConfigurationError(
                        f"{cls.__name__}.enqueue() would write on connection {write_connection.connection_alias!r}, "
                        "which has no open transaction, "
                        f"while connection {connection_alias!r} has one - the event would commit on its own, "
                        "not with that transaction's write. Pass using= naming that transaction's connection, "
                        f"or put {cls.__name__} on the connection of the models it reports on."
                    )
        return write_connection

    @classmethod
    async def signal_wakeup(
        cls, connection: DatabaseClient, topics: Iterable[str], wakeup: OutboxWakeup | None = None
    ) -> None:
        """Signals the relays that events of ``topics`` were written - once ``connection``'s transaction
        commits, at once outside a transaction.

        Args:
            connection: The connection the events were written on.
            topics: Their topics.
            wakeup: The wakeup, the model's ``Meta.outbox_wakeup`` when None.
        """
        wakeup = wakeup if wakeup is not None else cls.get_wakeup()
        if wakeup is not None:
            await wakeup.signal_written(connection, topics)

    @staticmethod
    def validate_enqueue_options(
        topic: str,
        idempotency_key: str | None,
        ordering_key: str | None,
        headers: Mapping[str, Any] | None,
        extra_field_values: Mapping[str, Any] | None,
    ) -> None:
        """Checks ``enqueue()``'s arguments.

        Raises:
            ValidationError: An argument has the wrong type or is out of range.
        """
        extra_field_names = set(extra_field_values or ())
        argument_field_names = sorted(ENQUEUE_ARGUMENT_FIELD_NAMES & extra_field_names)
        if argument_field_names:
            raise ValidationError(
                f"extra_field_values can't set {', '.join(argument_field_names)} - pass them as enqueue() arguments"
            )
        relay_managed_field_names = sorted(RELAY_MANAGED_FIELD_NAMES & extra_field_names)
        if relay_managed_field_names:
            raise ValidationError(
                f"extra_field_values can't set {', '.join(relay_managed_field_names)} - the ORM and "
                "OutboxRelay maintain them"
            )
        for argument_name, value, required in (
            ("topic", topic, True),
            ("idempotency_key", idempotency_key, False),
            ("ordering_key", ordering_key, False),
        ):
            if (value is not None or required) and (
                not isinstance(value, str) or not 1 <= len(value) <= OUTBOX_KEY_MAX_LENGTH
            ):
                raise ValidationError(
                    f"{argument_name} must be a string of 1..{OUTBOX_KEY_MAX_LENGTH} characters, got {value!r}"
                )
        if headers is not None and (
            not isinstance(headers, Mapping) or not all(isinstance(name, str) and name for name in headers)
        ):
            raise ValidationError(f"headers must be a mapping of non-empty text names, got {headers!r}")

    @classmethod
    async def insert_or_get_by_idempotency_key(
        cls,
        topic: str,
        payload: Any,
        idempotency_key: str,
        ordering_key: str | None,
        headers: dict[str, Any],
        write_connection: DatabaseClient,
        field_values: Mapping[str, Any],
    ) -> tuple[Self, bool]:
        """Inserts an event with ``idempotency_key`` unless one already exists, then reads it back.

        Args:
            topic: The topic of a new event.
            payload: The payload of a new event.
            idempotency_key: The unique key.
            ordering_key: The ordering key of a new event.
            headers: The headers of a new event.
            write_connection: The connection - possibly a transaction - both statements run on.
            field_values: Subclass column values of a new event.

        Returns:
            The event stored under the key, and whether this call inserted it.

        Raises:
            IntegrityError: The key is taken by an event not visible to this call.
            ConfigurationError: ``Meta.tenant_field`` is set, ``field_values`` names no tenant and
                no tenant scope is active; or the named tenant conflicts with the active scope.
        """
        if cls._meta.tenant_field and Tenancy.get_scope(cls) is None:
            tenant_given, given_tenant, _ = Tenancy.get_given_tenant(cls, dict(field_values))
            if tenant_given and given_tenant is not None:
                # An explicitly named tenant is trusted with no active scope, as create() does.
                with Tenancy.scope(given_tenant):
                    return await cls.insert_or_get_by_idempotency_key(
                        topic, payload, idempotency_key, ordering_key, headers, write_connection, field_values
                    )
        candidate = cls(
            topic=topic,
            payload=payload,
            idempotency_key=idempotency_key,
            ordering_key=ordering_key,
            headers=headers,
            **field_values,
        )
        # RETURNING tells exactly whether the row was written - where bulk_create() can return rows
        # at all, which needs the database to return them in the order they were written.
        read_back_inserted_row = write_connection.features.guarantees_returning_order
        conflict_field_names = cls.get_idempotency_conflict_field_names()
        await cls.objects.using(write_connection).bulk_create(
            [candidate],
            ignore_conflicts=True,
            on_conflict=conflict_field_names,
            returning=True if read_back_inserted_row else None,
        )
        # The row stored under the key is the one the insert conflicted with - the same values of
        # every field the key is unique with (a tenant, under a scope showing several).
        stored_row_filter = {field_name: getattr(candidate, field_name) for field_name in conflict_field_names}
        queryset = cls.objects.filter(**stored_row_filter).using(write_connection)
        if cls._meta.soft_delete_field:
            queryset = queryset.include_deleted()
        stored = await queryset.first()
        if stored is None:
            raise IntegrityError(
                f"{cls.__name__}.enqueue(): idempotency_key {idempotency_key!r} is already used by an event "
                "not visible here (another tenant's, or committed after this transaction's snapshot)"
            )
        if read_back_inserted_row:
            is_new = candidate._saved_in_db
        else:
            # An explicit id alone can't tell this insert apart from an earlier event stored under the
            # same key and id - the created_at this insert wrote can.
            is_new = stored.id == candidate.id and stored.created_at == candidate.created_at
        return stored, is_new

    @classmethod
    def get_idempotency_conflict_field_names(cls) -> list[str]:
        """The unique field set ``idempotency_key`` conflicts on.

        Returns:
            ``["idempotency_key"]`` for a unique column, otherwise the fields of the first
            unconditional ``UniqueConstraint`` that includes it.

        Raises:
            ConfigurationError: No unique constraint covers ``idempotency_key``.
        """
        if cls._meta.fields_map["idempotency_key"].unique:
            return ["idempotency_key"]
        for constraint in cls._meta.constraints:
            if (
                isinstance(constraint, UniqueConstraint)
                and constraint.condition is None
                and "idempotency_key" in constraint.fields
            ):
                return list(constraint.fields)
        raise ConfigurationError(
            f"{cls.__name__}.idempotency_key isn't unique - enqueue(idempotency_key=...) needs a unique "
            "constraint covering it to deduplicate on"
        )

    def __repr__(self) -> str:
        return f"<{type(self).__name__} id={self.id} topic={self.topic!r} published_at={self.published_at!r}>"
