from __future__ import annotations

from typing import ClassVar

from hare.exceptions import UnSupportedError
from hare.fields.db_defaults.sql_default import SqlDefault


class UuidV7(SqlDefault):
    """A time-ordered version 7 UUID as a ``db_default`` - generated by the database per row; rows
    inserted later get greater UUIDs, so an index over them grows at its end. Standard SQL has no
    such expression - a dialect registers a renderer for it (PostgreSQL 18+).

    Example::

        class Event(Model):
            id = fields.UUIDField(primary_key=True, db_default=UuidV7())
    """

    #: The ``Features`` flag of a server generating it.
    required_feature: ClassVar[str] = "supports_uuid_v7"

    def __init__(self) -> None:
        super().__init__("")

    def get_standard_sql(self) -> str:
        raise UnSupportedError("UuidV7() has no standard SQL - the dialect has no renderer for it")

    def __repr__(self) -> str:
        return "UuidV7()"

    def __eq__(self, other: object) -> bool:
        return isinstance(other, UuidV7)

    def __hash__(self) -> int:
        return hash("UuidV7")
