from __future__ import annotations

from typing import Any, ClassVar, TypeVar

from hare.dialects.clickhouse.enums import ClickhouseDialectName
from hare.fields.data.numeric.big_int_field import BigIntField

TInt = TypeVar("TInt", int, int | None)


class ClickhouseIntegerField(BigIntField[TInt]):
    """An integer of one of ClickHouse's own integer types - the values its type holds
    (``COLUMN_TYPE_RANGE``) are checked before they are written. Never generated by the database."""

    SUPPORTED_DIALECTS = frozenset({ClickhouseDialectName.CLICKHOUSE})
    COLUMN_TYPE_RANGE: ClassVar[tuple[int, int]]

    @property
    def constraints(self) -> dict[str, Any]:
        lowest, highest = self.COLUMN_TYPE_RANGE
        return {"ge": lowest, "le": highest}
